// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCytHr2PfZJrAOjdsRL0TuVF7yvKl16mq8',
    appId: '1:949745220079:web:24e329ec0ca7f000af9e1a',
    messagingSenderId: '949745220079',
    projectId: 'eduverse-69022',
    authDomain: 'eduverse-69022.firebaseapp.com',
    storageBucket: 'eduverse-69022.appspot.com',
    measurementId: 'G-1XWCGZPP7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeZJ7yU-ZCLBlG_3jrZlhFBBkVPq1J1Ig',
    appId: '1:949745220079:android:9c47f87f11ce35c5af9e1a',
    messagingSenderId: '949745220079',
    projectId: 'eduverse-69022',
    storageBucket: 'eduverse-69022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIvVbOqd5vjyPF-MQkkvSkGnHiiDq540',
    appId: '1:949745220079:ios:574ce70e145faa3baf9e1a',
    messagingSenderId: '949745220079',
    projectId: 'eduverse-69022',
    storageBucket: 'eduverse-69022.appspot.com',
    iosBundleId: 'com.example.eduverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmIvVbOqd5vjyPF-MQkkvSkGnHiiDq540',
    appId: '1:949745220079:ios:1d89157353b30c4caf9e1a',
    messagingSenderId: '949745220079',
    projectId: 'eduverse-69022',
    storageBucket: 'eduverse-69022.appspot.com',
    iosBundleId: 'com.example.eduverse.RunnerTests',
  );
}
